# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
title: Lihui Chen (陈黎辉)
first_name: Lihui
last_name: Chen
email: lihuichen@126.com
description: > # 简短描述，用于SEO
  Master's Supervisor at Chongqing University. Research focus: Image Restoration, Deep Learning, Multimodal Large Models.

# Footer settings
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username:  # 填写你的Github用户名
google_scholar_id: # 建议去 Google Scholar 复制你的 ID 填在这里
scholar_userid:    # 同上
# -----------------------------------------------------------------------------
# Analytics and Comments
# -----------------------------------------------------------------------------
# 如果需要开启 Google Analytics 或 Disqus评论，可以在这里配置
